apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequelize
spec:
  selector:
    matchLabels:
      app: sequelize
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sequelize
    spec:
      containers:
      - name: sequelize
        image: luismartorano/sequelize:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sequelize
  labels:
    app: sequelize
spec:
  type: ClusterIP
  selector:
    app: sequelize
  ports:
    - protocol: TCP
      name: sequelize
      port: 3000
      targetPort: 3000
